services:
  web:
    build: .
    tty: true
    volumes:
      - ./app:/app
    ports:
      - "5000:5000"
  postgres:
    image: postgres:15
    build: .
    restart: always
    environment:
      TZ: Asia/Tokyo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./db/postgres:/var/lib/postgresql/data
      - ./db/logs:/var/log
    ports:
      - 5432:5432